In [250]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [251]:
df=pd.read_csv('/content/dirty_v3_path.csv')
df

,Age,Gender,Medical Condition,Glucose,Blood Pressure,BMI,Oxygen Saturation,LengthOfStay,Cholesterol,Triglycerides,HbA1c,Smoking,Alcohol,Physical Activity,Diet Score,Family History,Stress Level,Sleep Hours,random_notes,noise_col
0,46.0,Male,Diabetes,137.04,135.27,28.90,96.04,6,231.88,210.56,7.61,0,0,-0.20,3.54,0,5.07,6.05,lorem,-137.057211
1,22.0,Male,Healthy,71.58,113.27,26.29,97.54,2,165.57,129.41,4.91,0,0,8.12,5.90,0,5.87,7.72,ipsum,-11.230610
2,50.0,NaN,Asthma,95.24,NaN,22.53,90.31,2,214.94,165.35,5.60,0,0,5.01,4.65,1,3.09,4.82,ipsum,98.331195
3,57.0,NaN,Obesity,NaN,130.53,38.47,96.60,5,197.71,182.13,6.92,0,0,3.16,3.37,0,3.01,5.33,lorem,44.187175
4,66.0,Female,Hypertension,95.15,178.17,31.12,94.90,4,259.53,115.85,5.98,0,1,3.56,3.40,0,6.38,6.64,lorem,44.831426
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,54.0,Female,Healthy,86.35,127.68,28.30,94.36,1,218.60,152.82,4.85,0,0,9.15,10.35,0,3.65,8.71,ipsum,89.573837
29996,41.0,Male,Asthma,89.24,154.37,24.93,96.07,4,198.30,176.81,5.36,1,0,3.34,3.40,0,6.72,2.81,lorem,-5.864517
29997,83.0,Female,NaN,NaN,170.11,30.55,97.83,3,210.13,168.76,5.05,0,0,4.53,4.50,0,4.31,3.61,###,-30.934595
29998,41.0,Male,Diabetes,242.87,152.97,23.57,99.17,3,208.86,224.21,7.59,0,0,3.16,2.59,0,7.10,5.80,ipsum,5.085258


In [252]:
df.isna().sum()

,0
Age,4500
Gender,4500
Medical Condition,4500
Glucose,4500
Blood Pressure,4500
BMI,0
Oxygen Saturation,0
LengthOfStay,0
Cholesterol,0
Triglycerides,0


In [253]:
df.dtypes

,0
Age,float64
Gender,object
Medical Condition,object
Glucose,float64
Blood Pressure,float64
BMI,float64
Oxygen Saturation,float64
LengthOfStay,int64
Cholesterol,float64
Triglycerides,float64


In [254]:
df.shape

(30000, 20)

In [255]:
df['Age'].unique()

array([46., 22., 50., 57., 66., 80., 60., 13., 58., 32., 37., 74., 53.,
       45., 64., nan, 51., 63., 78., 82., 33., 62., 73., 25., 39., 86.,
       12., 52., 56., 41., 42., 55., 34., 24., 35., 72., 84., 79., 75.,
       54., 48., 30., 61., 49., 69., 31., 10., 70., 20., 77., 15., 71.,
       65., 23., 59., 83., 44., 28., 36., 38., 67., 85., 47., 81., 40.,
       68., 18., 89., 88., 76., 43., 27., 29., 21., 19., 26., 14., 87.,
       17., 11., 16.])

In [256]:
df['Gender'].value_counts()

,count
Gender,
Female,12865
Male,12635


In [257]:
df['Medical Condition'].value_counts()

,count
Medical Condition,
Hypertension,7120
Diabetes,6417
Obesity,3857
Healthy,3039
Asthma,2037
Arthritis,1796
Cancer,1234


In [258]:
df['Glucose'].unique()

array([137.04,  71.58,  95.24, ..., 156.08, 119.96, 242.87])

In [259]:
df['Blood Pressure'].unique()

array([135.27, 113.27,    nan, ..., 169.77, 185.1 , 158.76])

In [260]:
df['Physical Activity'].unique()

array([-0.2 ,  8.12,  5.01, ..., -1.11, -1.96, 10.32])

In [261]:
df['Physical Activity'] = df['Physical Activity'].apply(lambda x: 0 if x < 0 else x)


In [262]:
df['Sleep Hours']=df['Sleep Hours'].round().astype(int)

In [263]:
df['Age'] = df['Age'].fillna(df['Age'].mode()[0])
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Glucose']=df['Glucose'].fillna(df['Glucose'].mean())
df['Blood Pressure']=df['Blood Pressure'].fillna(df['Blood Pressure'].mean())
df['Physical Activity']=df['Physical Activity'].fillna(df['Physical Activity'].mean())
df=df.dropna(subset=['Medical Condition'])
df

,Age,Gender,Medical Condition,Glucose,Blood Pressure,BMI,Oxygen Saturation,LengthOfStay,Cholesterol,Triglycerides,HbA1c,Smoking,Alcohol,Physical Activity,Diet Score,Family History,Stress Level,Sleep Hours,random_notes,noise_col
0,46.0,Male,Diabetes,137.040000,135.270000,28.90,96.04,6,231.88,210.56,7.61,0,0,0.00,3.54,0,5.07,6,lorem,-137.057211
1,22.0,Male,Healthy,71.580000,113.270000,26.29,97.54,2,165.57,129.41,4.91,0,0,8.12,5.90,0,5.87,8,ipsum,-11.230610
2,50.0,Female,Asthma,95.240000,140.455337,22.53,90.31,2,214.94,165.35,5.60,0,0,5.01,4.65,1,3.09,5,ipsum,98.331195
3,57.0,Female,Obesity,123.622179,130.530000,38.47,96.60,5,197.71,182.13,6.92,0,0,3.16,3.37,0,3.01,5,lorem,44.187175
4,66.0,Female,Hypertension,95.150000,178.170000,31.12,94.90,4,259.53,115.85,5.98,0,1,3.56,3.40,0,6.38,7,lorem,44.831426
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,76.0,Female,Hypertension,97.170000,138.920000,25.65,93.99,3,235.65,238.26,6.43,0,0,3.14,3.46,0,6.66,6,ipsum,37.705013
29995,54.0,Female,Healthy,86.350000,127.680000,28.30,94.36,1,218.60,152.82,4.85,0,0,9.15,10.35,0,3.65,9,ipsum,89.573837
29996,41.0,Male,Asthma,89.240000,154.370000,24.93,96.07,4,198.30,176.81,5.36,1,0,3.34,3.40,0,6.72,3,lorem,-5.864517
29998,41.0,Male,Diabetes,242.870000,152.970000,23.57,99.17,3,208.86,224.21,7.59,0,0,3.16,2.59,0,7.10,6,ipsum,5.085258


In [264]:
df.drop(['random_notes','noise_col'],axis=1,inplace=True)
df

/tmp/ipykernel_363/701783798.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['random_notes','noise_col'],axis=1,inplace=True)


,Age,Gender,Medical Condition,Glucose,Blood Pressure,BMI,Oxygen Saturation,LengthOfStay,Cholesterol,Triglycerides,HbA1c,Smoking,Alcohol,Physical Activity,Diet Score,Family History,Stress Level,Sleep Hours
0,46.0,Male,Diabetes,137.040000,135.270000,28.90,96.04,6,231.88,210.56,7.61,0,0,0.00,3.54,0,5.07,6
1,22.0,Male,Healthy,71.580000,113.270000,26.29,97.54,2,165.57,129.41,4.91,0,0,8.12,5.90,0,5.87,8
2,50.0,Female,Asthma,95.240000,140.455337,22.53,90.31,2,214.94,165.35,5.60,0,0,5.01,4.65,1,3.09,5
3,57.0,Female,Obesity,123.622179,130.530000,38.47,96.60,5,197.71,182.13,6.92,0,0,3.16,3.37,0,3.01,5
4,66.0,Female,Hypertension,95.150000,178.170000,31.12,94.90,4,259.53,115.85,5.98,0,1,3.56,3.40,0,6.38,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29994,76.0,Female,Hypertension,97.170000,138.920000,25.65,93.99,3,235.65,238.26,6.43,0,0,3.14,3.46,0,6.66,6
29995,54.0,Female,Healthy,86.350000,127.680000,28.30,94.36,1,218.60,152.82,4.85,0,0,9.15,10.35,0,3.65,9
29996,41.0,Male,Asthma,89.240000,154.370000,24.93,96.07,4,198.30,176.81,5.36,1,0,3.34,3.40,0,6.72,3
29998,41.0,Male,Diabetes,242.870000,152.970000,23.57,99.17,3,208.86,224.21,7.59,0,0,3.16,2.59,0,7.10,6


In [265]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Gender'] = lab.fit_transform(df['Gender'])
df['Medical Condition'] = lab.fit_transform(df['Medical Condition'])

/tmp/ipykernel_363/3553110720.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = lab.fit_transform(df['Gender'])
/tmp/ipykernel_363/3553110720.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Medical Condition'] = lab.fit_transform(df['Medical Condition'])


In [266]:
df.dtypes

,0
Age,float64
Gender,int64
Medical Condition,int64
Glucose,float64
Blood Pressure,float64
BMI,float64
Oxygen Saturation,float64
LengthOfStay,int64
Cholesterol,float64
Triglycerides,float64


In [267]:
x=df.drop(['Medical Condition'], axis=1)
y=df['Medical Condition']

In [268]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [269]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
x_train_res,y_train_res = smote.fit_resample(x_train,y_train)

In [270]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train_res)
x_train_res = scaler.transform(x_train_res)
x_test = scaler.transform(x_test)

In [271]:
import tensorflow as tf

In [272]:
from keras.models import Sequential
from keras.layers import Dense

In [273]:
ann=Sequential()

In [274]:
ann.add(Dense(17,activation='relu'))
ann.add(Dense(16,activation='relu'))
ann.add(Dense(8,activation='relu'))
ann.add(Dense(4,activation='relu'))
ann.add(Dense(7,activation='softmax'))

In [275]:
ann.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [276]:
ann.fit(x_train_res,y_train_res,epochs=30,batch_size=30)

Epoch 1/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.5033 - loss: 1.3213
Epoch 2/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8954 - loss: 0.3965
Epoch 3/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9133 - loss: 0.2656
Epoch 4/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9201 - loss: 0.2367
Epoch 5/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9248 - loss: 0.2246
Epoch 6/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.9277 - loss: 0.2159
Epoch 7/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.9281 - loss: 0.2031
Epoch 8/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9314 - loss: 0.1967
Epoch 9/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9278 - loss: 0.2027
Epoch 10/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9314 - loss: 0.1883
Epoch 11/30
1322/1322 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9330 - loss: 0.1925
Epoch 12/30
1322/1322 ━━━━━━━━

In [277]:
ann.evaluate(x_test,y_test)


160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8936 - loss: 0.3041


[0.28490275144577026, 0.9003921747207642]